### ISSUE TITLE
ReactWindows support

### ISSUE THREAD

**Issue by quincycs** [exponentjs/exp#19]
Yay the XDE works on the Windows OS!

Now it would be nice if the universal windows platform flavor of react native would work with exponentjs.  Maybe at least limited support?

**Comment by ide** [comment]
Hey Quincy, we're not planning to work on this yet though one day we'd like to support more platforms than Android & iOS. We see those platforms being our biggest audience by far though so we're putting all of our time towards Android & iOS and Exponent services to begin with. It'd be more work than we can commit to in order to do a good job on limited support for UWP, so it's not a project we can take on right now. Sorry about that.

In the meantime we do plan to support XDE on Mac/Windows/Linux so you'll be able to make Android & iOS apps with Exponent on Windows.

**Comment by quincycs** [comment]
Thx James!
